<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>swift</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bswift</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Swift</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#root</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((@)available)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.attribute.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.swift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.swift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute.available.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.platform.os.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.swift</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b((?:iOS|macOS|OSX|watchOS|tvOS)(?:ApplicationExtension)?)\b(?:\s+([0-9]+(?:\.[0-9]+)*\b))?</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(introduced|deprecated|obsoleted)\s*(:)\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?!\G)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b[0-9]+(?:\.[0-9]+)*\b</string>
									<key>name</key>
									<string>constant.numeric.swift</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(message|renamed)\s*(:)\s*(?=")</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?!\G)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#literals</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.platform.all.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.other.swift</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.character-not-allowed-here.swift</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:(\*)|\b(deprecated|unavailable)\b)\s*(.*?)(?=[,)])</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((@)objc)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.attribute.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.swift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.swift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute.objc.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.missing-colon-after-selector-piece.swift</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\w*(?::(?:\w*:)*(\w*))?</string>
							<key>name</key>
							<string>entity.name.function.swift</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(?&lt;q&gt;`?)[\p{L}_][\p{L}_\p{N}\p{M}]*(\k&lt;q&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.attribute.swift</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.identifier.swift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.identifier.swift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>any other attribute</string>
					<key>end</key>
					<string>(?!\G\()</string>
					<key>name</key>
					<string>meta.attribute.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.arguments.begin.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.arguments.end.swift</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.arguments.attribute.swift</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expressions</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.swift</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.swift</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.swift</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\A^(#!).*$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*\*(?!/)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.swift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nested</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.swift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.playground.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nested</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.swift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nested</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\*/</string>
					<key>name</key>
					<string>invalid.illegal.unexpected-end-of-block-comment.swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>///</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^</string>
							<key>name</key>
							<string>comment.line.triple-slash.documentation.swift</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>//:</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^</string>
							<key>name</key>
							<string>comment.line.double-slash.documentation.swift</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^</string>
							<key>name</key>
							<string>comment.line.double-slash.swift</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>nested</key>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nested</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>compiler-control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#)(if|elseif)\s+(false)\b.*?(?=$|//|/\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.conditional.swift</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.preprocessor.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.preprocessor.conditional.swift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.swift</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>comment.block.preprocessor.swift</string>
					<key>end</key>
					<string>(?=^\s*(#(elseif|else|endif)\b))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(#)(if|elseif)\s+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.preprocessor.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.preprocessor.conditional.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*(?://|/\*))|$</string>
					<key>name</key>
					<string>meta.preprocessor.conditional.swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(&amp;&amp;|\|\|)</string>
							<key>name</key>
							<string>keyword.operator.logical.swift</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(true|false)\b</string>
							<key>name</key>
							<string>constant.language.boolean.swift</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.condition.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.begin.swift</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.constant.platform.architecture.swift</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.end.swift</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(arch)\s*(\()\s*(?:(arm|arm64|powerpc64|powerpc64le|i386|x86_64|s390x)|\w+)\s*(\))</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.condition.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.begin.swift</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.constant.platform.os.swift</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.end.swift</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(os)\s*(\()\s*(?:(macOS|OSX|iOS|tvOS|watchOS|Android|Linux|FreeBSD|Windows|PS4)|\w+)\s*(\))</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(swift)\s*(\()</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.condition.swift</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.begin.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\))|$</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.end.swift</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>&gt;=</string>
									<key>name</key>
									<string>keyword.operator.comparison.swift</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b[0-9]+(?:\.[0-9]+)*\b</string>
									<key>name</key>
									<string>constant.numeric.swift</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.preprocessor.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.preprocessor.conditional.swift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\S+</string>
									<key>name</key>
									<string>invalid.illegal.character-not-allowed-here.swift</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(#)(else|endif)(.*?)(?=$|//|/\*)</string>
					<key>name</key>
					<string>meta.preprocessor.conditional.swift</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.preprocessor.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.preprocessor.sourcelocation.swift</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.swift</string>
						</dict>
						<key>5</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(file)\s*(:)\s*(?=")</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>support.variable.parameter.swift</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.swift</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?!\G)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#literals</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>support.variable.parameter.swift</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.swift</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>constant.numeric.integer.swift</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(line)\s*(:)\s*([0-9]+)</string>
								</dict>
								<dict>
									<key>match</key>
									<string>,</string>
									<key>name</key>
									<string>punctuation.separator.parameters.swift</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\S+</string>
									<key>name</key>
									<string>invalid.illegal.character-not-allowed-here.swift</string>
								</dict>
							</array>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.swift</string>
						</dict>
						<key>7</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\S+</string>
									<key>name</key>
									<string>invalid.illegal.character-not-allowed-here.swift</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(#)(sourceLocation)((\()([^)]*)(\)))(.*?)(?=$|//|/\*)</string>
					<key>name</key>
					<string>meta.preprocessor.sourcelocation.swift</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:if|else|guard|where|switch|case|default|fallthrough)\b</string>
					<key>name</key>
					<string>keyword.control.branch.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:continue|break|fallthrough|return)\b</string>
					<key>name</key>
					<string>keyword.control.transfer.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:while|repeat|for|in)\b</string>
					<key>name</key>
					<string>keyword.control.loop.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bdefer\b</string>
					<key>name</key>
					<string>keyword.control.defer.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:do|catch|throws?|rethrows|try)\b|\btry[?!]\B</string>
					<key>name</key>
					<string>keyword.control.exception.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:associatedtype|let|operator|typealias|var)\b</string>
					<key>name</key>
					<string>keyword.other.declaration-specifier.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(class|enum|extension|precedencegroup|protocol|struct)\b</string>
					<key>name</key>
					<string>storage.type.$1.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:inout|static|final|lazy|mutating|nonmutating|optional|indirect|required|override|dynamic|convenience|infix|prefix|postfix)\b</string>
					<key>name</key>
					<string>storage.modifier.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\binit[?!]|\b(?:func|init|deinit|subscript|didSet|get|set|willSet)\b</string>
					<key>name</key>
					<string>storage.type.function.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:fileprivate|private|internal|public|open)\b</string>
					<key>name</key>
					<string>keyword.other.declaration-specifier.accessibility.swift</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>matches weak, unowned, unowned(safe), unowned(unsafe)</string>
					<key>match</key>
					<string>\b(?:weak\b|unowned(?:\((?:un)?safe\))?)</string>
					<key>name</key>
					<string>keyword.other.capture-specifier.swift</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.metatype.swift</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\.)(?:(dynamicType|self)|(Protocol|Type))\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:super|self|Self)\b</string>
					<key>name</key>
					<string>variable.language.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\B(?:#file|#line|#column|#function|#dsohandle)\b|\b(?:__FILE__|__LINE__|__COLUMN__|__FUNCTION__|__DSO_HANDLE__)\b</string>
					<key>name</key>
					<string>support.variable.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bimport\b</string>
					<key>name</key>
					<string>keyword.control.import.swift</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bnil\b</string>
					<key>name</key>
					<string>constant.language.nil.swift</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>object "literals" used in playgrounds</string>
					<key>match</key>
					<string>\B#(colorLiteral|imageLiteral|fileLiteral)\b</string>
					<key>name</key>
					<string>support.function.object-literal.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\B#keyPath\b</string>
					<key>name</key>
					<string>support.function.key-path.swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\B(#selector)(\()(?:\s*(getter|setter)\s*(:))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.selector-reference.swift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.swift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.variable.parameter.swift</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.argument-label.swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.swift</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>boolean</key>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.swift</string>
				</dict>
				<key>numeric</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>0.1, -4_2.5, 6.022e23, 10E-5</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)[0-9][0-9_]*(?=\.[0-9]|[eE])(?:\.[0-9][0-9_]*)?(?:[eE][-+]?[0-9][0-9_]*)?\b(?!\.[0-9])</string>
							<key>name</key>
							<string>constant.numeric.float.decimal.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>-0x1.ap2_3, 0x31p-4</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)(0x\h[\h_]*)(?:\.\h[\h_]*)?[pP][-+]?[0-9][0-9_]*\b(?!\.[0-9])</string>
							<key>name</key>
							<string>constant.numeric.float.hexadecimal.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>0x1p, 0x1p_2, 0x1.5pa, 0x1.1p+1f, 0x1pz</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)(0x\h[\h_]*)(?:\.\h[\h_]*)?(?:[pP][-+]?\w*)\b(?!\.[0-9])</string>
							<key>name</key>
							<string>invalid.illegal.numeric.float.invalid-exponent.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>0x1.5w (note that 0x1.f may be a valid expression)</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)(0x\h[\h_]*)\.[0-9][\w.]*</string>
							<key>name</key>
							<string>invalid.illegal.numeric.float.missing-exponent.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>-.5, .2f (note that 1.-.5 may be a valid expression)</string>
							<key>match</key>
							<string>(?&lt;=\s|^)\-?\.[0-9][\w.]*</string>
							<key>name</key>
							<string>invalid.illegal.numeric.float.missing-leading-zero.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>0b_0_1, 0x_1p+3q</string>
							<key>match</key>
							<string>(\B\-|\b)0[box]_[\h_]*(?:[pPeE][+-]?\w+)?[\w.]+</string>
							<key>name</key>
							<string>invalid.illegal.numeric.leading-underscore.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>tuple positional member: not really a numeric literal, but not invalid</string>
							<key>match</key>
							<string>(?&lt;=[\[\](){}\p{L}_\p{N}\p{M}]\.)[0-9]+\b</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>0b010, 0b1_0</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)0b[01][01_]*\b(?!\.[0-9])</string>
							<key>name</key>
							<string>constant.numeric.integer.binary.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>0o1, 0o7_3</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)0o[0-7][0-7_]*\b(?!\.[0-9])</string>
							<key>name</key>
							<string>constant.numeric.integer.octal.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>02, 3_456</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)[0-9][0-9_]*\b(?!\.[0-9])</string>
							<key>name</key>
							<string>constant.numeric.integer.decimal.swift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>0x4, 0xF_7</string>
							<key>match</key>
							<string>(\B\-|\b)(?&lt;![\[\](){}\p{L}_\p{N}\p{M}]\.)0x\h[\h_]*\b(?!\.[0-9])</string>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.swift</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\B\-|\b)[0-9][\w.]*</string>
							<key>name</key>
							<string>invalid.illegal.numeric.other.swift</string>
						</dict>
					</array>
				</dict>
				<key>string</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>"</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.swift</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.double.swift</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\r|\n</string>
									<key>name</key>
									<string>invalid.illegal.returns-not-allowed.swift</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\[0\\tnr"']</string>
									<key>name</key>
									<string>constant.character.escape.swift</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\u\{\h{1,8}\}</string>
									<key>name</key>
									<string>constant.character.escape.unicode.swift</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.embedded.begin.swift</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>source.swift</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>#root</string>
												</dict>
											</array>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.embedded.end.swift</string>
										</dict>
										<key>6</key>
										<dict>
											<key>name</key>
											<string>source.swift</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(?x)
										(\\\()							# Opening
										(
											(?&lt;parens&gt;
												(
													[^()"]				# Anything except parens
												  | \(					# Matched pairs of parens
													\g&lt;parens&gt;			#  …that can be nested
													\)
												  | "					# Strings
													([^\\]|\\.)*		# Contents allowing for escapes
													"
												)*
											)
										)
										((\)))							# Closing
									</string>
									<key>name</key>
									<string>meta.embedded.line.swift</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\.</string>
									<key>name</key>
									<string>invalid.illegal.escape-not-recognized</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Type casting</string>
					<key>match</key>
					<string>\b(is\b|as([!?]\B|\b))</string>
					<key>name</key>
					<string>keyword.operator.type-casting.swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
						(?=
							(?&lt;oph&gt;								# operator-head
								[/=\-+!*%&lt;&gt;&amp;|^~?]
							  | [\x{00A1}-\x{00A7}]
							  | [\x{00A9}\x{00AB}]
							  | [\x{00AC}\x{00AE}]
							  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
							  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
							  | [\x{2030}-\x{203E}]
							  | [\x{2041}-\x{2053}]
							  | [\x{2055}-\x{205E}]
							  | [\x{2190}-\x{23FF}]
							  | [\x{2500}-\x{2775}]
							  | [\x{2794}-\x{2BFF}]
							  | [\x{2E00}-\x{2E7F}]
							  | [\x{3001}-\x{3003}]
							  | [\x{3008}-\x{3030}]
							)
						  | \.
							(
								\g&lt;oph&gt;							# operator-head
							  | \.
							  | [\x{0300}-\x{036F}]				# operator-character
							  | [\x{1DC0}-\x{1DFF}]
							  | [\x{20D0}-\x{20FF}]
							  | [\x{FE00}-\x{FE0F}]
							  | [\x{FE20}-\x{FE2F}]
							  | [\x{E0100}-\x{E01EF}]
							)
						)
					</string>
					<key>comment</key>
					<string>This rule helps us speed up the matching.</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G(\+\+|\-\-)$</string>
											<key>name</key>
											<string>keyword.operator.increment-or-decrement.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(\+|\-)$</string>
											<key>name</key>
											<string>keyword.operator.arithmetic.unary.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G!$</string>
											<key>name</key>
											<string>keyword.operator.logical.not.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G~$</string>
											<key>name</key>
											<string>keyword.operator.bitwise.not.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>.+</string>
											<key>name</key>
											<string>keyword.operator.custom.prefix.swift</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Prefix unary operator</string>
							<key>match</key>
							<string>(?x)
								\G										# Matching from the beginning ensures
																		# that we start with operator-head
								(?&lt;=^|[\s(\[{,;:])
								(
									(?!(//|/\*|\*/))
									(
										[/=\-+!*%&lt;&gt;&amp;|^~?]				# operator-head
									  | [\x{00A1}-\x{00A7}]
									  | [\x{00A9}\x{00AB}]
									  | [\x{00AC}\x{00AE}]
									  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
									  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
									  | [\x{2030}-\x{203E}]
									  | [\x{2041}-\x{2053}]
									  | [\x{2055}-\x{205E}]
									  | [\x{2190}-\x{23FF}]
									  | [\x{2500}-\x{2775}]
									  | [\x{2794}-\x{2BFF}]
									  | [\x{2E00}-\x{2E7F}]
									  | [\x{3001}-\x{3003}]
									  | [\x{3008}-\x{3030}]
								  
									  | [\x{0300}-\x{036F}]				# operator-character
									  | [\x{1DC0}-\x{1DFF}]
									  | [\x{20D0}-\x{20FF}]
									  | [\x{FE00}-\x{FE0F}]
									  | [\x{FE20}-\x{FE2F}]
									  | [\x{E0100}-\x{E01EF}]
									)
								)++
								(?![\s)\]},;:]|\z)
							</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G(\+\+|\-\-)$</string>
											<key>name</key>
											<string>keyword.operator.increment-or-decrement.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G!$</string>
											<key>name</key>
											<string>keyword.operator.increment-or-decrement.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>.+</string>
											<key>name</key>
											<string>keyword.operator.custom.postfix.swift</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Postfix unary operator</string>
							<key>match</key>
							<string>(?x)
								\G										# Matching from the beginning ensures
																		# that we start with operator-head
								(?&lt;!^|[\s(\[{,;:])
								(
									(?!(//|/\*|\*/))
									(
										[/=\-+!*%&lt;&gt;&amp;|^~?]				# operator-head
									  | [\x{00A1}-\x{00A7}]
									  | [\x{00A9}\x{00AB}]
									  | [\x{00AC}\x{00AE}]
									  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
									  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
									  | [\x{2030}-\x{203E}]
									  | [\x{2041}-\x{2053}]
									  | [\x{2055}-\x{205E}]
									  | [\x{2190}-\x{23FF}]
									  | [\x{2500}-\x{2775}]
									  | [\x{2794}-\x{2BFF}]
									  | [\x{2E00}-\x{2E7F}]
									  | [\x{3001}-\x{3003}]
									  | [\x{3008}-\x{3030}]
								  
									  | [\x{0300}-\x{036F}]				# operator-character
									  | [\x{1DC0}-\x{1DFF}]
									  | [\x{20D0}-\x{20FF}]
									  | [\x{FE00}-\x{FE0F}]
									  | [\x{FE20}-\x{FE2F}]
									  | [\x{E0100}-\x{E01EF}]
									)
								)++
								(?=[\s)\]},;:]|\z)
							</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G=$</string>
											<key>name</key>
											<string>keyword.operator.assignment.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(\+|\-|\*|/|%|&lt;&lt;|&gt;&gt;|&amp;|\^|\||&amp;&amp;|\|\|)=$</string>
											<key>name</key>
											<string>keyword.operator.assignment.compound.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(\+|\-|\*|/)$</string>
											<key>name</key>
											<string>keyword.operator.arithmetic.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G&amp;(\+|\-|\*)$</string>
											<key>name</key>
											<string>keyword.operator.arithmetic.overflow.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G%$</string>
											<key>name</key>
											<string>keyword.operator.arithmetic.remainder.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(==|!=|&gt;|&lt;|&gt;=|&lt;=|~=)$</string>
											<key>name</key>
											<string>keyword.operator.comparison.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G\?\?$</string>
											<key>name</key>
											<string>keyword.operator.coalescing.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(&amp;&amp;|\|\|)$</string>
											<key>name</key>
											<string>keyword.operator.logical.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(&amp;|\||\^|&lt;&lt;|&gt;&gt;)$</string>
											<key>name</key>
											<string>keyword.operator.bitwise.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G(===|!==)$</string>
											<key>name</key>
											<string>keyword.operator.bitwise.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\G\?$</string>
											<key>name</key>
											<string>keyword.operator.ternary.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>.+</string>
											<key>name</key>
											<string>keyword.operator.custom.infix.swift</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Infix operator</string>
							<key>match</key>
							<string>(?x)
								\G										# Matching from the beginning ensures
																		# that we start with operator-head
								(
									(?!(//|/\*|\*/))
									(
										[/=\-+!*%&lt;&gt;&amp;|^~?]				# operator-head
									  | [\x{00A1}-\x{00A7}]
									  | [\x{00A9}\x{00AB}]
									  | [\x{00AC}\x{00AE}]
									  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
									  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
									  | [\x{2030}-\x{203E}]
									  | [\x{2041}-\x{2053}]
									  | [\x{2055}-\x{205E}]
									  | [\x{2190}-\x{23FF}]
									  | [\x{2500}-\x{2775}]
									  | [\x{2794}-\x{2BFF}]
									  | [\x{2E00}-\x{2E7F}]
									  | [\x{3001}-\x{3003}]
									  | [\x{3008}-\x{3030}]
								  
									  | [\x{0300}-\x{036F}]				# operator-character
									  | [\x{1DC0}-\x{1DFF}]
									  | [\x{20D0}-\x{20FF}]
									  | [\x{FE00}-\x{FE0F}]
									  | [\x{FE20}-\x{FE2F}]
									  | [\x{E0100}-\x{E01EF}]
									)
								)++
							</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>.+</string>
											<key>name</key>
											<string>keyword.operator.custom.prefix.dot.swift</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Dot prefix unary operator</string>
							<key>match</key>
							<string>(?x)
								\G										# Matching from the beginning ensures
																		# that we start with operator-head
								(?&lt;=^|[\s(\[{,;:])
								\.										# dot
								(
									(?!(//|/\*|\*/))
									(
										\.								# dot
									  | [/=\-+!*%&lt;&gt;&amp;|^~?]				# operator-head
									  | [\x{00A1}-\x{00A7}]
									  | [\x{00A9}\x{00AB}]
									  | [\x{00AC}\x{00AE}]
									  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
									  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
									  | [\x{2030}-\x{203E}]
									  | [\x{2041}-\x{2053}]
									  | [\x{2055}-\x{205E}]
									  | [\x{2190}-\x{23FF}]
									  | [\x{2500}-\x{2775}]
									  | [\x{2794}-\x{2BFF}]
									  | [\x{2E00}-\x{2E7F}]
									  | [\x{3001}-\x{3003}]
									  | [\x{3008}-\x{3030}]
								  
									  | [\x{0300}-\x{036F}]				# operator-character
									  | [\x{1DC0}-\x{1DFF}]
									  | [\x{20D0}-\x{20FF}]
									  | [\x{FE00}-\x{FE0F}]
									  | [\x{FE20}-\x{FE2F}]
									  | [\x{E0100}-\x{E01EF}]
									)
								)++
								(?![\s)\]},;:]|\z)
							</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>.+</string>
											<key>name</key>
											<string>keyword.operator.custom.postfix.dot.swift</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Dot postfix unary operator</string>
							<key>match</key>
							<string>(?x)
								\G										# Matching from the beginning ensures
																		# that we start with operator-head
								(?&lt;!^|[\s(\[{,;:])
								\.										# dot
								(
									(?!(//|/\*|\*/))
									(
										\.								# dot
									  | [/=\-+!*%&lt;&gt;&amp;|^~?]				# operator-head
									  | [\x{00A1}-\x{00A7}]
									  | [\x{00A9}\x{00AB}]
									  | [\x{00AC}\x{00AE}]
									  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
									  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
									  | [\x{2030}-\x{203E}]
									  | [\x{2041}-\x{2053}]
									  | [\x{2055}-\x{205E}]
									  | [\x{2190}-\x{23FF}]
									  | [\x{2500}-\x{2775}]
									  | [\x{2794}-\x{2BFF}]
									  | [\x{2E00}-\x{2E7F}]
									  | [\x{3001}-\x{3003}]
									  | [\x{3008}-\x{3030}]
								  
									  | [\x{0300}-\x{036F}]				# operator-character
									  | [\x{1DC0}-\x{1DFF}]
									  | [\x{20D0}-\x{20FF}]
									  | [\x{FE00}-\x{FE0F}]
									  | [\x{FE20}-\x{FE2F}]
									  | [\x{E0100}-\x{E01EF}]
									)
								)++
								(?=[\s)\]},;:]|\z)
							</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G\.\.[.&lt;]$</string>
											<key>name</key>
											<string>keyword.operator.range.swift</string>
										</dict>
										<dict>
											<key>match</key>
											<string>.+</string>
											<key>name</key>
											<string>keyword.operator.custom.infix.dot.swift</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Dot infix operator</string>
							<key>match</key>
							<string>(?x)
								\G										# Matching from the beginning ensures
																		# that we start with operator-head
								\.										# dot
								(
									(?!(//|/\*|\*/))
									(
										\.								# dot
									  | [/=\-+!*%&lt;&gt;&amp;|^~?]				# operator-head
									  | [\x{00A1}-\x{00A7}]
									  | [\x{00A9}\x{00AB}]
									  | [\x{00AC}\x{00AE}]
									  | [\x{00B0}-\x{00B1}\x{00B6}\x{00BB}\x{00BF}\x{00D7}\x{00F7}]
									  | [\x{2016}-\x{2017}\x{2020}-\x{2027}]
									  | [\x{2030}-\x{203E}]
									  | [\x{2041}-\x{2053}]
									  | [\x{2055}-\x{205E}]
									  | [\x{2190}-\x{23FF}]
									  | [\x{2500}-\x{2775}]
									  | [\x{2794}-\x{2BFF}]
									  | [\x{2E00}-\x{2E7F}]
									  | [\x{3001}-\x{3003}]
									  | [\x{3008}-\x{3030}]
								  
									  | [\x{0300}-\x{036F}]				# operator-character
									  | [\x{1DC0}-\x{1DFF}]
									  | [\x{20D0}-\x{20FF}]
									  | [\x{FE00}-\x{FE0F}]
									  | [\x{FE20}-\x{FE2F}]
									  | [\x{E0100}-\x{E01EF}]
									)
								)++
							</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.operator.ternary.swift</string>
				</dict>
			</array>
		</dict>
		<key>root</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#compiler-control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.swift</string>
	<key>uuid</key>
	<string>8C743E89-9C8D-4833-8149-6500D82AA463</string>
</dict>
</plist>
