<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>SwiftDoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(/\*(\*|!))\s*$</string>
			<key>comment</key>
			<string>Documentation comment block</string>
			<key>end</key>
			<string>\s*(\*/)\s*$</string>
			<key>name</key>
			<string>comment.block.documentation.swiftdoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inlinecode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.restructuredtext#all</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*///\s*</string>
			<key>comment</key>
			<string>In-line doc comment</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.triple-slash.swiftdoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inlinecode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.restructuredtext#all</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.double-slash.swift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.marker.swiftdoc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Special pragma-style comment</string>
			<key>match</key>
			<string>\s*(//)\s+(MARK|TODO|FIXME):(.*)$</string>
			<key>name</key>
			<string>comment.line.marker.swiftdoc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inlinecode</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.restructuredtext</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>inline literal</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>markup.raw.restructuredtext</string>
		</dict>
	</dict>
	<key>scope</key>
	<string>source.swift</string>
	<key>scopeName</key>
	<string>text.restructuredtext.swiftdoc</string>
	<key>uuid</key>
	<string>0489F7E9-43E1-4001-9911-D1EC8E712F76</string>
</dict>
</plist>
